# Generated by Django 5.0.4 on 2024-06-04 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_tipoproduto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.tipoproduto'),
        ),
    ]
